### ISSUE TITLE
Unpaired reads

### ISSUE THREAD

**Issue by averagehat** [necrolyte2/subsamplebam#1]
Currently subsamplebam does not distinguish between orphaned (unpaired) and paired reads. But the ngs_mapper pipeline (specifically `bam_to_depth` and `samtools mpileup` only acknowledge paired reads. In this case, subsamplebam may subsample orphaned reads, giving less than the expected coverage depth from `mpileup`. Subsamplebam's behavior should be consistent with `mpileup`, and pick only paired reads unless otherwise specified.

__Plan:__ My pull request will ignore unpaired reads by default. The "-A" flag (consistent with `mpileup`) will force it to consider unpaired reads.

**Comment by necrolyte2** [comment]
This sounds right to me
